/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Licenses = {
  _id: string;
  _type: "licenses";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<{
    title: string;
    issuer: string;
    description: string;
    number?: string;
    icon: "gavel" | "ticket" | "store";
    _key: string;
  }>;
};

export type Features = {
  _id: string;
  _type: "features";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<{
    title: string;
    description: string;
    icon:
      | "save"
      | "review"
      | "fees"
      | "verify"
      | "track"
      | "meters"
      | "bolt"
      | "payment"
      | "verified_user"
      | "tag";
    _key: string;
  }>;
};

export type Testimonials = {
  _id: string;
  _type: "testimonials";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  items?: Array<{
    name: string;
    role?: string;
    city?: string;
    date?: string;
    rating?: number;
    quote: string;
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type LegalPage = {
  _id: string;
  _type: "legalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description: string;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
  >;
  accordion?: Array<{
    question: string;
    answer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
  };
  publishedAt: string;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
  >;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  author?: AuthorReference;
  broadcastSentAt?: string;
  broadcastId?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  role?: string;
  bio?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  fees?: {
    residentialFirstGov: number;
    residentialFirstCompany: number;
    residentialExtraGov: number;
    residentialExtraCompany: number;
    commercialFirstGov: number;
    commercialFirstCompany: number;
    commercialExtraGov: number;
    commercialExtraCompany: number;
  };
  supportPhone?: string;
  email?: string;
  regaLicenseUrl?: string;
  cta?: {
    note?: string;
    residentialFrom?: number;
    commercialFrom?: number;
  };
  marketingPoints?: Array<{
    text: string;
    icon:
      | "save"
      | "review"
      | "fees"
      | "verify"
      | "track"
      | "meters"
      | "bolt"
      | "payment"
      | "verified_user"
      | "tag";
    _key: string;
  }>;
  faqs?: Array<{
    question: string;
    answer: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _key: string;
  }>;
  gaMeasurementId?: string;
  gtmId?: string;
  socialLinks?: Array<{
    platform:
      | "facebook"
      | "instagram"
      | "youtube"
      | "linkedin"
      | "tiktok"
      | "x"
      | "snapchat"
      | "whatsapp"
      | "threads";
    url?: string;
    _key: string;
  }>;
};

export type Subscriber = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email: string;
  status: "pending" | "confirmed" | "unsubscribed";
  confirmToken?: string;
  tokenExpiresAt?: string;
  source?: string;
  resendContactId?: string;
};

export type ContactMessage = {
  _id: string;
  _type: "contactMessage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  phone: string;
  email?: string;
  message: string;
  status: "new" | "read" | "replied";
  submittedAt: string;
};

export type RentalRequest = {
  _id: string;
  _type: "rentalRequest";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  requestNo: string;
  contractType: "residential" | "commercial";
  status: "new" | "reviewing" | "approved" | "completed" | "cancelled";
  submittedAt: string;
  applicant?: {
    role:
      | "\u0623\u0646\u0627 \u0627\u0644\u0645\u0627\u0644\u0643 \u0623\u0648 \u0645\u0645\u062B\u0644\u0647"
      | "\u0623\u0646\u0627 \u0627\u0644\u0645\u0633\u062A\u0623\u062C\u0631";
    isAgent?: boolean;
    agencyNumber?: string;
    phone: string;
    nationalId: string;
    dob?: string;
    ownerIban?: string;
  };
  counterparty?: {
    counterType: "\u0641\u0631\u062F" | "\u0645\u0646\u0634\u0623\u0629";
    nationalId?: string;
    phone?: string;
    dob?: string;
    ownerIban?: string;
    unifiedNumber?: string;
    entityName?: string;
    repId?: string;
    repPhone?: string;
    repDob?: string;
    authNumber?: string;
  };
  property?: {
    deedNumber?: string;
    deedDate?: string;
    propertyType?: string;
    propertyCustom?: string;
    unitType?: string;
    unitCustom?: string;
    unitNumber?: string;
    floor?: string;
    floorCustom?: string;
    area?: number;
    rooms?: string;
    roomsCustom?: number;
    extras?: Array<{
      kind: string;
      count: number;
      _key: string;
    }>;
    kitchenCabinets?: boolean;
    electroMeter?: string;
    waterMeter?: string;
  };
  location?: {
    locationManual?: boolean;
    mapsLink?: string;
    city?: string;
    buildingNumber?: string;
    additionalNumber?: string;
    postalCode?: string;
  };
  terms?: {
    duration?: string;
    customMonths?: number;
    contractStart?: string;
    payment?: string;
    annualRent?: number;
    feeBreakdown?: {
      years?: number;
      government?: number;
      company?: number;
      total?: number;
    };
    notes?: string;
  };
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Licenses
  | Features
  | Testimonials
  | SanityImageAssetReference
  | LegalPage
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | CategoryReference
  | AuthorReference
  | Post
  | Author
  | SiteSettings
  | Subscriber
  | ContactMessage
  | RentalRequest
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_id == "siteSettings"][0]{ fees, supportPhone, email, regaLicenseUrl, cta{ note, residentialFrom, commercialFrom }, marketingPoints[]{ text, icon }, gaMeasurementId, gtmId, socialLinks[]{ platform, url }, faqs[]{ _key, question, answer[]{ _key, _type, ..., markDefs[]{ _key, ... } } } }
export type SITE_SETTINGS_QUERY_RESULT =
  | {
      fees: null;
      supportPhone: null;
      email: null;
      regaLicenseUrl: null;
      cta: null;
      marketingPoints: null;
      gaMeasurementId: null;
      gtmId: null;
      socialLinks: null;
      faqs: null;
    }
  | {
      fees: null;
      supportPhone: null;
      email: string;
      regaLicenseUrl: null;
      cta: null;
      marketingPoints: null;
      gaMeasurementId: null;
      gtmId: null;
      socialLinks: null;
      faqs: null;
    }
  | {
      fees: null;
      supportPhone: null;
      email: string | null;
      regaLicenseUrl: null;
      cta: null;
      marketingPoints: null;
      gaMeasurementId: null;
      gtmId: null;
      socialLinks: null;
      faqs: null;
    }
  | {
      fees: {
        residentialFirstGov: number;
        residentialFirstCompany: number;
        residentialExtraGov: number;
        residentialExtraCompany: number;
        commercialFirstGov: number;
        commercialFirstCompany: number;
        commercialExtraGov: number;
        commercialExtraCompany: number;
      } | null;
      supportPhone: string | null;
      email: string | null;
      regaLicenseUrl: string | null;
      cta: {
        note: string | null;
        residentialFrom: number | null;
        commercialFrom: number | null;
      } | null;
      marketingPoints: Array<{
        text: string;
        icon:
          | "bolt"
          | "fees"
          | "meters"
          | "payment"
          | "review"
          | "save"
          | "tag"
          | "track"
          | "verified_user"
          | "verify";
      }> | null;
      gaMeasurementId: string | null;
      gtmId: string | null;
      socialLinks: Array<{
        platform:
          | "facebook"
          | "instagram"
          | "linkedin"
          | "snapchat"
          | "threads"
          | "tiktok"
          | "whatsapp"
          | "x"
          | "youtube";
        url: string | null;
      }> | null;
      faqs: Array<{
        _key: string;
        question: string;
        answer: Array<{
          _key: string;
          _type: "block";
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h4" | "normal";
          listItem?: "bullet" | "number";
          markDefs: Array<{
            _key: string;
            href?: string;
            _type: "link";
          }> | null;
          level?: number;
        }>;
      }> | null;
    }
  | null;

// Source: sanity/lib/queries.ts
// Variable: REQUESTS_ALL_QUERY
// Query: *[_type == "rentalRequest"] | order(submittedAt desc){    _id,    requestNo,    contractType,    status,    submittedAt  }
export type REQUESTS_ALL_QUERY_RESULT = Array<{
  _id: string;
  requestNo: string;
  contractType: "commercial" | "residential";
  status: "approved" | "cancelled" | "completed" | "new" | "reviewing";
  submittedAt: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: POSTS_INDEX_QUERY
// Query: *[_type == "post" && defined(slug.current) && defined(publishedAt)] | order(publishedAt desc)[$offset...$end]{    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    cover{ alt, caption, asset-> },    categories[]->{ _id, title, "slug": slug.current },    author->{ name, role }  }
export type POSTS_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  cover: {
    alt: string;
    caption: string | null;
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  author: {
    name: string;
    role: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POSTS_COUNT_QUERY
// Query: count(*[_type == "post" && defined(slug.current) && defined(publishedAt)])
export type POSTS_COUNT_QUERY_RESULT = number;

// Source: sanity/lib/queries.ts
// Variable: LATEST_POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current) && defined(publishedAt)] | order(publishedAt desc)[0...6]{    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    cover{ alt, caption, asset-> },    categories[]->{ _id, title, "slug": slug.current },    author->{ name, role }  }
export type LATEST_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  cover: {
    alt: string;
    caption: string | null;
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  author: {
    name: string;
    role: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)][].slug.current
export type POST_SLUGS_QUERY_RESULT = Array<string>;

// Source: sanity/lib/queries.ts
// Variable: LEGAL_PAGES_NAV_QUERY
// Query: *[_type == "legalPage" && defined(slug.current)] | order(_createdAt asc){    _id,    title,    "slug": slug.current  }
export type LEGAL_PAGES_NAV_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: LEGAL_PAGE_QUERY
// Query: *[_type == "legalPage" && slug.current == $slug][0]{    _id,    title,    description,    content[]{      _key,      _type,      ...,      markDefs[]{        _key,        ...,        _type == "link" => { "href": @.href }      },      _type == "image" => { asset-> }    },    accordion[]{ _key, question, answer[]{ _key, _type, ..., markDefs[]{ _key, ... } } }  }
export type LEGAL_PAGE_QUERY_RESULT = {
  _id: string;
  title: string;
  description: string;
  content: Array<
    | {
        _key: string;
        _type: "block";
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<{
          _key: string;
          href: string | null;
          _type: "link";
        }> | null;
        level?: number;
      }
    | {
        _key: string;
        _type: "image";
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash: string;
          extension: string;
          mimeType: string;
          size: number;
          assetId: string;
          uploadId?: string;
          path: string;
          url: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        markDefs: null;
      }
  > | null;
  accordion: Array<{
    _key: string;
    question: string;
    answer: Array<{
      _key: string;
      _type: "block";
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h4" | "normal";
      listItem?: "bullet" | "number";
      markDefs: Array<{
        _key: string;
        href?: string;
        _type: "link";
      }> | null;
      level?: number;
    }>;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: POST_DETAIL_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    cover{ alt, caption, asset-> },    categories[]->{ _id, title, "slug": slug.current },    author->{ name, role, bio, avatar{ alt, asset-> } },    body[]{      _key,      _type,      ...,      markDefs[]{        _key,        ...,        _type == "link" => { "href": @.href }      },      _type == "image" => { asset-> }    }  }
export type POST_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  cover: {
    alt: string;
    caption: string | null;
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  author: {
    name: string;
    role: string | null;
    bio: string | null;
    avatar: {
      alt: string;
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
    } | null;
  } | null;
  body: Array<
    | {
        _key: string;
        _type: "block";
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<{
          _key: string;
          href: string | null;
          _type: "link";
        }> | null;
        level?: number;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        _key: string;
        _type: "image";
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash: string;
          extension: string;
          mimeType: string;
          size: number;
          assetId: string;
          uploadId?: string;
          path: string;
          url: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        markDefs: null;
      }
  >;
} | null;

// Source: sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(title asc){    _id,    title,    "slug": slug.current,    description,    "postCount": count(*[_type == "post" && references(^._id) && defined(publishedAt)])  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  description: string | null;
  postCount: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: POSTS_BY_CATEGORY_QUERY
// Query: *[_type == "post" && defined(slug.current) && defined(publishedAt) && $categorySlug in categories[]->slug.current] | order(publishedAt desc){    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    cover{ alt, caption, asset-> },    categories[]->{ _id, title, "slug": slug.current },    author->{ name, role }  }
export type POSTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  cover: {
    alt: string;
    caption: string | null;
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string;
    slug: string;
  }> | null;
  author: {
    name: string;
    role: string | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: REQUEST_DETAIL_QUERY
// Query: *[_type == "rentalRequest" && requestNo == $requestNo][0]{    requestNo,    contractType,    status,    submittedAt,    applicant{ role, isAgent, agencyNumber, phone, nationalId, dob, ownerIban },    counterparty{      counterType, nationalId, phone, dob, ownerIban, unifiedNumber,      entityName, repId, repPhone, repDob, authNumber    },    property{      deedNumber, deedDate, propertyType, propertyCustom, unitType, unitCustom,      unitNumber, floor, floorCustom, area, rooms, roomsCustom,      extras[]{ kind, count }, kitchenCabinets,      electroMeter, waterMeter    },    location{ locationManual, mapsLink, city, buildingNumber, additionalNumber, postalCode },    terms{      duration, customMonths, contractStart, payment, annualRent,      feeBreakdown{ years, government, company, total }, notes    }  }
export type REQUEST_DETAIL_QUERY_RESULT = {
  requestNo: string;
  contractType: "commercial" | "residential";
  status: "approved" | "cancelled" | "completed" | "new" | "reviewing";
  submittedAt: string;
  applicant: {
    role:
      | "\u0623\u0646\u0627 \u0627\u0644\u0645\u0627\u0644\u0643 \u0623\u0648 \u0645\u0645\u062B\u0644\u0647"
      | "\u0623\u0646\u0627 \u0627\u0644\u0645\u0633\u062A\u0623\u062C\u0631";
    isAgent: boolean | null;
    agencyNumber: string | null;
    phone: string;
    nationalId: string;
    dob: string | null;
    ownerIban: string | null;
  } | null;
  counterparty: {
    counterType: "\u0641\u0631\u062F" | "\u0645\u0646\u0634\u0623\u0629";
    nationalId: string | null;
    phone: string | null;
    dob: string | null;
    ownerIban: string | null;
    unifiedNumber: string | null;
    entityName: string | null;
    repId: string | null;
    repPhone: string | null;
    repDob: string | null;
    authNumber: string | null;
  } | null;
  property: {
    deedNumber: string | null;
    deedDate: string | null;
    propertyType: string | null;
    propertyCustom: string | null;
    unitType: string | null;
    unitCustom: string | null;
    unitNumber: string | null;
    floor: string | null;
    floorCustom: string | null;
    area: number | null;
    rooms: string | null;
    roomsCustom: number | null;
    extras: Array<{
      kind: string;
      count: number;
    }> | null;
    kitchenCabinets: boolean | null;
    electroMeter: string | null;
    waterMeter: string | null;
  } | null;
  location: {
    locationManual: boolean | null;
    mapsLink: string | null;
    city: string | null;
    buildingNumber: string | null;
    additionalNumber: string | null;
    postalCode: string | null;
  } | null;
  terms: {
    duration: string | null;
    customMonths: number | null;
    contractStart: string | null;
    payment: string | null;
    annualRent: number | null;
    feeBreakdown: {
      years: number | null;
      government: number | null;
      company: number | null;
      total: number | null;
    } | null;
    notes: string | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: REQUEST_STATUS_QUERY
// Query: *[_type == "rentalRequest" && requestNo == $requestNo][0]{    requestNo,    contractType,    status,    submittedAt,    "feeTotal": terms.feeBreakdown.total,    "annualRent": terms.annualRent  }
export type REQUEST_STATUS_QUERY_RESULT = {
  requestNo: string;
  contractType: "commercial" | "residential";
  status: "approved" | "cancelled" | "completed" | "new" | "reviewing";
  submittedAt: string;
  feeTotal: number | null;
  annualRent: number | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: SUBSCRIBER_BY_EMAIL_QUERY
// Query: *[_type == "subscriber" && email == $email][0]{ _id, email, status, confirmToken, tokenExpiresAt, resendContactId }
export type SUBSCRIBER_BY_EMAIL_QUERY_RESULT = {
  _id: string;
  email: string;
  status: "confirmed" | "pending" | "unsubscribed";
  confirmToken: string | null;
  tokenExpiresAt: string | null;
  resendContactId: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: SUBSCRIBER_BY_TOKEN_QUERY
// Query: *[_type == "subscriber" && confirmToken == $tok][0]{ _id, email, status, confirmToken, tokenExpiresAt, resendContactId }
export type SUBSCRIBER_BY_TOKEN_QUERY_RESULT = {
  _id: string;
  email: string;
  status: "confirmed" | "pending" | "unsubscribed";
  confirmToken: string | null;
  tokenExpiresAt: string | null;
  resendContactId: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: BROADCAST_CANDIDATE_QUERY
// Query: *[_type == "post" && _id == $id][0]{ _id, title, "slug": slug.current, excerpt, cover, publishedAt, broadcastSentAt, broadcastId }
export type BROADCAST_CANDIDATE_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
  } | null;
  publishedAt: string;
  broadcastSentAt: string | null;
  broadcastId: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_id == "testimonials"][0]{    items[]{ _key, name, role, city, date, rating, quote }  }
export type TESTIMONIALS_QUERY_RESULT =
  | {
      items: null;
    }
  | {
      items: Array<{
        _key: string;
        name: null;
        role: null;
        city: null;
        date: null;
        rating: null;
        quote: null;
      }> | null;
    }
  | {
      items: Array<{
        _key: string;
        name: string;
        role: string | null;
        city: string | null;
        date: string | null;
        rating: number | null;
        quote: string;
      }> | null;
    }
  | null;

// Source: sanity/lib/queries.ts
// Variable: FEATURES_QUERY
// Query: *[_id == "features"][0]{    items[]{ _key, title, description, icon }  }
export type FEATURES_QUERY_RESULT =
  | {
      items: null;
    }
  | {
      items: Array<{
        _key: string;
        title: null;
        description: null;
        icon: null;
      }> | null;
    }
  | {
      items: Array<{
        _key: string;
        title: string;
        description: string;
        icon:
          | "bolt"
          | "fees"
          | "meters"
          | "payment"
          | "review"
          | "save"
          | "tag"
          | "track"
          | "verified_user"
          | "verify";
      }> | null;
    }
  | {
      items: Array<{
        _key: string;
        title: string;
        description: string;
        icon: "gavel" | "store" | "ticket";
      }> | null;
    }
  | null;

// Source: sanity/lib/queries.ts
// Variable: LICENSES_QUERY
// Query: *[_id == "licenses"][0]{    items[]{ _key, title, issuer, description, number, icon }  }
export type LICENSES_QUERY_RESULT =
  | {
      items: null;
    }
  | {
      items: Array<{
        _key: string;
        title: null;
        issuer: null;
        description: null;
        number: null;
        icon: null;
      }> | null;
    }
  | {
      items: Array<{
        _key: string;
        title: string;
        issuer: null;
        description: string;
        number: null;
        icon:
          | "bolt"
          | "fees"
          | "meters"
          | "payment"
          | "review"
          | "save"
          | "tag"
          | "track"
          | "verified_user"
          | "verify";
      }> | null;
    }
  | {
      items: Array<{
        _key: string;
        title: string;
        issuer: string;
        description: string;
        number: string | null;
        icon: "gavel" | "store" | "ticket";
      }> | null;
    }
  | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_id == "siteSettings"][0]{ fees, supportPhone, email, regaLicenseUrl, cta{ note, residentialFrom, commercialFrom }, marketingPoints[]{ text, icon }, gaMeasurementId, gtmId, socialLinks[]{ platform, url }, faqs[]{ _key, question, answer[]{ _key, _type, ..., markDefs[]{ _key, ... } } } }': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "rentalRequest"] | order(submittedAt desc){\n    _id,\n    requestNo,\n    contractType,\n    status,\n    submittedAt\n  }': REQUESTS_ALL_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current) && defined(publishedAt)] | order(publishedAt desc)[$offset...$end]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    cover{ alt, caption, asset-> },\n    categories[]->{ _id, title, "slug": slug.current },\n    author->{ name, role }\n  }': POSTS_INDEX_QUERY_RESULT;
    'count(*[_type == "post" && defined(slug.current) && defined(publishedAt)])': POSTS_COUNT_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current) && defined(publishedAt)] | order(publishedAt desc)[0...6]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    cover{ alt, caption, asset-> },\n    categories[]->{ _id, title, "slug": slug.current },\n    author->{ name, role }\n  }': LATEST_POSTS_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)][].slug.current': POST_SLUGS_QUERY_RESULT;
    '*[_type == "legalPage" && defined(slug.current)] | order(_createdAt asc){\n    _id,\n    title,\n    "slug": slug.current\n  }': LEGAL_PAGES_NAV_QUERY_RESULT;
    '*[_type == "legalPage" && slug.current == $slug][0]{\n    _id,\n    title,\n    description,\n    content[]{\n      _key,\n      _type,\n      ...,\n      markDefs[]{\n        _key,\n        ...,\n        _type == "link" => { "href": @.href }\n      },\n      _type == "image" => { asset-> }\n    },\n    accordion[]{ _key, question, answer[]{ _key, _type, ..., markDefs[]{ _key, ... } } }\n  }': LEGAL_PAGE_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    cover{ alt, caption, asset-> },\n    categories[]->{ _id, title, "slug": slug.current },\n    author->{ name, role, bio, avatar{ alt, asset-> } },\n    body[]{\n      _key,\n      _type,\n      ...,\n      markDefs[]{\n        _key,\n        ...,\n        _type == "link" => { "href": @.href }\n      },\n      _type == "image" => { asset-> }\n    }\n  }': POST_DETAIL_QUERY_RESULT;
    '*[_type == "category"] | order(title asc){\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "postCount": count(*[_type == "post" && references(^._id) && defined(publishedAt)])\n  }': CATEGORIES_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current) && defined(publishedAt) && $categorySlug in categories[]->slug.current] | order(publishedAt desc){\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    cover{ alt, caption, asset-> },\n    categories[]->{ _id, title, "slug": slug.current },\n    author->{ name, role }\n  }': POSTS_BY_CATEGORY_QUERY_RESULT;
    '*[_type == "rentalRequest" && requestNo == $requestNo][0]{\n    requestNo,\n    contractType,\n    status,\n    submittedAt,\n    applicant{ role, isAgent, agencyNumber, phone, nationalId, dob, ownerIban },\n    counterparty{\n      counterType, nationalId, phone, dob, ownerIban, unifiedNumber,\n      entityName, repId, repPhone, repDob, authNumber\n    },\n    property{\n      deedNumber, deedDate, propertyType, propertyCustom, unitType, unitCustom,\n      unitNumber, floor, floorCustom, area, rooms, roomsCustom,\n      extras[]{ kind, count }, kitchenCabinets,\n      electroMeter, waterMeter\n    },\n    location{ locationManual, mapsLink, city, buildingNumber, additionalNumber, postalCode },\n    terms{\n      duration, customMonths, contractStart, payment, annualRent,\n      feeBreakdown{ years, government, company, total }, notes\n    }\n  }': REQUEST_DETAIL_QUERY_RESULT;
    '*[_type == "rentalRequest" && requestNo == $requestNo][0]{\n    requestNo,\n    contractType,\n    status,\n    submittedAt,\n    "feeTotal": terms.feeBreakdown.total,\n    "annualRent": terms.annualRent\n  }': REQUEST_STATUS_QUERY_RESULT;
    '*[_type == "subscriber" && email == $email][0]{ _id, email, status, confirmToken, tokenExpiresAt, resendContactId }': SUBSCRIBER_BY_EMAIL_QUERY_RESULT;
    '*[_type == "subscriber" && confirmToken == $tok][0]{ _id, email, status, confirmToken, tokenExpiresAt, resendContactId }': SUBSCRIBER_BY_TOKEN_QUERY_RESULT;
    '*[_type == "post" && _id == $id][0]{ _id, title, "slug": slug.current, excerpt, cover, publishedAt, broadcastSentAt, broadcastId }': BROADCAST_CANDIDATE_QUERY_RESULT;
    '*[_id == "testimonials"][0]{\n    items[]{ _key, name, role, city, date, rating, quote }\n  }': TESTIMONIALS_QUERY_RESULT;
    '*[_id == "features"][0]{\n    items[]{ _key, title, description, icon }\n  }': FEATURES_QUERY_RESULT;
    '*[_id == "licenses"][0]{\n    items[]{ _key, title, issuer, description, number, icon }\n  }': LICENSES_QUERY_RESULT;
  }
}
